version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "shadowing-api-dev"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
